feat: show error after submit. show message to the user
everydotorg/donate-button pull request #100
Opened 2021-02-10 13:37 UTC by martinbianchi

closes #97 

I also added a validation for amounts greater than 1,000,000

2021-02-10 13:45 UTC, osdiab approved these changes
Will merge once docs are built and committed

2021-02-10 13:45 UTC, osdiab commented on packages/donate-button/src/components/Input/input.css
> +    border-color: orangered!important
Ideally styles wouldn't need !important, I'll add a lint rule banning that later, but it's fine for now given that a lot of the styles will likely be revamped when tackling removing style injector in #77

2021-02-11 01:02 UTC, osdiab requested changes
tried it out, still some UX issues - see here

https://app.usebubbles.com/q9tZwqXLSNVRLqMit4cyG1/comments-on-every-month-git-mbianchi-error-message-p22-verce

2021-02-11 11:30 UTC, martinbianchi commented
@osdiab I saw the video, but seems that the changes weren't impacted. The same with #103 . Could be something wrong with the deployment? Or should I do something before push the changes?

2021-02-14 10:00 UTC, osdiab commented
Oh yeah maybe the Vercel demo isn't working unless you build and commit? I'll check tomorrow if that's the case, would be better if it weren't.

2021-02-15 07:09 UTC, osdiab commented
oh, i see - the vercel instance run by p22 (`every-month`) doesn't update but the one run by us at Every.org (`donate-button`) does. @jake-nz can you turn off the `every-month` vercel instance?

2021-02-15 07:09 UTC, osdiab commented
I'll merge this but follow up issue, the error messages shouldn't cause the button to move.

2021-02-15 07:19 UTC, merged

2021-02-15 07:55 UTC, jake-nz commented
> oh, i see - the vercel instance run by p22 (`every-month`) doesn't update but the one run by us at Every.org (`donate-button`) does. @jake-nz can you turn off the `every-month` vercel instance?

Done ✅